package com.beanoung.crm.workbench.mapper;

import com.beanoung.crm.workbench.pojo.Clue;
import com.beanoung.crm.workbench.pojo.ClueRemark;
import com.beanoung.crm.workbench.pojo.ClueRemarkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClueRemarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Wed Nov 30 12:01:15 CST 2022
     */
    int countByExample(ClueRemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Wed Nov 30 12:01:15 CST 2022
     */
    int deleteByExample(ClueRemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Wed Nov 30 12:01:15 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Wed Nov 30 12:01:15 CST 2022
     */
    int insert(ClueRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Wed Nov 30 12:01:15 CST 2022
     */
    int insertSelective(ClueRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Wed Nov 30 12:01:15 CST 2022
     */
    List<ClueRemark> selectByExample(ClueRemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Wed Nov 30 12:01:15 CST 2022
     */
    ClueRemark selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Wed Nov 30 12:01:15 CST 2022
     */
    int updateByExampleSelective(@Param("record") ClueRemark record, @Param("example") ClueRemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Wed Nov 30 12:01:15 CST 2022
     */
    int updateByExample(@Param("record") ClueRemark record, @Param("example") ClueRemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Wed Nov 30 12:01:15 CST 2022
     */
    int updateByPrimaryKeySelective(ClueRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Wed Nov 30 12:01:15 CST 2022
     */
    int updateByPrimaryKey(ClueRemark record);

    /**
     * 根据线索id查所有评论
     */
    List<ClueRemark> selectAllClueRemarkByClueId(String id);

    /**
     * 增
     */
    int insertClueRemark(ClueRemark clueRemark);

    /**
     * 删
     */
    int deleteClueRemarkByClueId(String clueId);

    /**
     * 根据线索id查所有评论,用于转移
     */
    List<ClueRemark> selectClueRemarkByClueIdForConvert(String clueId);

}