package com.beanoung.crm.workbench.mapper;

import com.beanoung.crm.workbench.pojo.Activity;
import com.beanoung.crm.workbench.pojo.Clue;
import com.beanoung.crm.workbench.pojo.ClueExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ClueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Thu Nov 24 15:57:11 CST 2022
     */
    int countByExample(ClueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Thu Nov 24 15:57:11 CST 2022
     */
    int deleteByExample(ClueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Thu Nov 24 15:57:11 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Thu Nov 24 15:57:11 CST 2022
     */
    int insert(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Thu Nov 24 15:57:11 CST 2022
     */
    int insertSelective(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Thu Nov 24 15:57:11 CST 2022
     */
    List<Clue> selectByExample(ClueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Thu Nov 24 15:57:11 CST 2022
     */
    Clue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Thu Nov 24 15:57:11 CST 2022
     */
    int updateByExampleSelective(@Param("record") Clue record, @Param("example") ClueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Thu Nov 24 15:57:11 CST 2022
     */
    int updateByExample(@Param("record") Clue record, @Param("example") ClueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Thu Nov 24 15:57:11 CST 2022
     */
    int updateByPrimaryKeySelective(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Thu Nov 24 15:57:11 CST 2022
     */
    int updateByPrimaryKey(Clue record);

    /**
     * 增
     */
    int insertClue(Clue clue);

    /**
     * 查询并分页
     */
    List<Clue> selectClueByConditionForPage(Map<String,Object> map);

    /**
     * 查询结果的条数
     */
    int selectCountOfClueByCondition(Map<String,Object> map);

    /**
     * 批量删除
     */
    int deleteClueByIds(String[] id);

    /**
     * 根据id查询线索,用于修改
     */
    Clue selectClueById(String id);

    /**
     * 保存修改
     */
    int updateClue(Clue clue);

    /**
     * 根据id查线索给详情页
     */
    Clue selectClueByIdForDetail(String clueId);

    /**
     * 查询线索用于转换
     */
    Clue selectClueByIdForConvert(String id);

    /**
     * 转换线索
     */
    int updateConvert(Map<String,Object> map);

    /**
     * 删
     */
    int deleteClueById(String clueId);
}